### PR TITLE
Milestone 2 - Friendship model and associations

### PR DESCRIPTION
**Pull request by jrai0792**
- In this milestone, I have added the Friendship model and its associations. 
- Logic for requesting the follow request.
- Added unit tests.

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @jrai0792  ! 👋 👋 

### You have done well so far :clap: However, there are changes required for you to make in order for this milestone to be approved. Kindly work on them and submit them for another code review.

**Recommended**

- [x] User model has_many :friendships ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)).

- [x] User model `has_many :inverted_friendships, class_name: "Friendship", foreign_key: "friend_id"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- [x] Friendship model `belongs_to :user` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- [x] There is a button to invite a user to friendship on users list page and on the single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- let's add these buttons to the mention views and make them work.

- [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)).


- The timeline should only have the login user's post and his or her friend's post so let's create these validations for the views.

- [x] The following and followers buttons are not registering the number of people following the signed-in user and those she's following.

**Test**

- [ ] I see you've created unit test cases with Rspec but let's also create integration test cases with Rspec and Capybara at least for the Friendship features (Send, Accept, and Reject a Friend Request and see user and friends post in the Timeline). Also, put actual tests in place of the empty test files or delete them. 
 


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Changes Required! :recycle:
### Hi @jrai0792 :clap: :clap:
#### Good job so far :-1: However, some of the required changes mentioned in the previous are not implemented. Check my comments below :point_down:

#### Tests:
- _Add more tests. Specifically, add tests for the controllers, integrations test that covers sign in, sign up, and friendship features (Send, Accept, and Reject a Friend Request and see user and friends post in the Timeline)._

#### Model:
**_Note: Simplify the user model to something similar to what is outlined in the specification :point_down: _**
**_The models should be defined as following or similar_**
- _User model `has_many :friendships` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))_

- _User model `has_many :inverted_friendships, class_name: "Friendship", foreign_key: "friend_id"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))_

- _Friendship model `belongs_to :user` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))_

- _Friendship model `belongs_to :friend, class_name: "User"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))_

#### App Behaviour:
- _There should a button to invite user to friendship on users list page, this button should be beside each user on the list and also the button should be available on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))_

- _The posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))_

#### _Reviewed by Temitayo Adeleke_

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
#### Hey there :wave: 
Thank you for putting in the effort in building out the feature requested for this project.
I can see that you have made some changes requested by the previous reviewer, however, there are still some changes to be made.
I will try my best to list the changes and explain what you need to do.
##### Tests:
- I tried running the tests but there was some error. I think it has to do with how you are requiring some of the dependencies for their test. Please check your test and update them to make them work.
##### Model
- Although your models and the associations you set up are working fine, it doesn't meet the specific requirements for this milestone. You were given [this](https://smartfunnycool.com/friendships-in-activerecord/) article to help you set up your friendship feature, and if you read the article you will notice that the way you set up your model is different from the way it was specified there. Try to set up your model similar to the way it is set up in the article i.e 
 User model `has_many :friendships`
 User model `has_many :inverted_friendships, class_name: "Friendship", foreign_key: "friend_id"` 
 Friendship model `belongs_to :user `
 Friendship model `belongs_to :friend, class_name: "User" `
- Posts timeline includes posts written by logged-in user and their friends. Currently, a logged-in user is only able to see the post of the users they are following, i.e that has accepted their friendship request, but those users are not able to see the posts of that logged-in user unless they too are following the logged-in user. This is because you have set up the friendship model just like the way it is on Twitter but it should be implemented just the way it is on Facebook i.e mutual friendship, where once I accept a friend request from a user, then we automatically have a mutual friendship. Please refer to the article that was provided to you and make changes accordingly.

Please do request another review once you are done making changes.
Happy coding :+1: 

slack(@ebeagusamuel)

**Comment by jrai0792** [comment]
> # Changes Required ♻️
> #### Hey there 👋
> Thank you for putting in the effort in building out the feature requested for this project.
> I can see that you have made some changes requested by the previous reviewer, however, there are still some changes to be made.
> I will try my best to list the changes and explain what you need to do.
> 
> ##### Tests:
> * I tried running the tests but there was some error. I think it has to do with how you are requiring some of the dependencies for their test. Please check your test and update them to make them work.
> 
> ##### Model
> * Although your models and the associations you set up are working fine, it doesn't meet the specific requirements for this milestone. You were given [this](https://smartfunnycool.com/friendships-in-activerecord/) article to help you set up your friendship feature, and if you read the article you will notice that the way you set up your model is different from the way it was specified there. Try to set up your model similar to the way it is set up in the article i.e
>   User model `has_many :friendships`
>   User model `has_many :inverted_friendships, class_name: "Friendship", foreign_key: "friend_id"`
>   Friendship model `belongs_to :user `
>   Friendship model `belongs_to :friend, class_name: "User" `
> * Posts timeline includes posts written by logged-in user and their friends. Currently, a logged-in user is only able to see the post of the users they are following, i.e that has accepted their friendship request, but those users are not able to see the posts of that logged-in user unless they too are following the logged-in user. This is because you have set up the friendship model just like the way it is on Twitter but it should be implemented just the way it is on Facebook i.e mutual friendship, where once I accept a friend request from a user, then we automatically have a mutual friendship. Please refer to the article that was provided to you and make changes accordingly.
> 
> Please do request another review once you are done making changes.
> Happy coding 👍
> 
> slack(@ebeagusamuel)

Hi,

> ##### Tests:
I ran the test in my machine, and they are working fine.

> ##### Model
>As per the requirement, it's not mentioned to have the model as similar to the article. As per my understanding, the article was for reference if struck.

>Also, I have not added the mutual friendship logic, as it is to be taken care of in the next milestone.

Thanks,

**Review by Georjane — APPROVED** [review]
## Status: PR Approved ✔️ ✔️
### Hi Team 🙌
Congratulations! 🎊 🎊 You have completed the minimum requirements for this project to be approved. You can go ahead and merge this PR.👍

Goodluck on your next project and Happy Coding 💻

**Pull request merged**
